print("¿Nombre del alumno? Elias Alain Vital Delgadillo")
print("¿Lugar de residencia? Pabellon de Hidalgo, la Hacienda")
print("¿Fecha de nacimiento? 27 de Junio de 2003")
print("¿Color favorito? Azul, Rojo y Verde")
print("¿Animal favorito? Aguila y la mayoria de reptiles")
print("¿Qué es la programación? Programación es la acción de programar que implica ordenar, estructurar o componer una serie de acciones cronológicas para cumplir un objetivo.")
print("¿Por qué es importante la programación? Es el arte de crear soluciones desde cero a paradigmas complejos a base de un pensamiento estructurado, lógico y creativo.")
print("Explique con sus palabras que es herencia. Es el pasar la idea o el codigo base de algo para seguir mejorando este, se podria decir que es como la evolucion pero con la idea de logrando alcanzar nuevos atributos los cuales van a seguir obteniendo mas y mas con el pasar del tiempo.")
print("Explique con sus palabras que es poliformismo. Se refiere a la propiedad por la que es posible enviar mensajes sintácticamente iguales a objetos de tipos distintos")
print("Explique con sus palabras que es abstracción. Es un termino que hace referencia a la ocultación de la complejidad intrínseca de una aplicación al exterior, centrándose sólo en como puede ser usada, lo que se conoce como interfaz.")
print("Explique con sus palabras que es encapsulamiento. Es el almacenar toda la informacion en un grupo a y otra en un grupo b separando estas con la informacion necesario para dar un producto final el cual es c")